site_name: Tailor Workflow Gallery
nav:
  - Intro: index.md
  - Workflows:
      - Software Integration:
           -  Run orcaflex in paralell: Workflows/software_integration/run_orcaflex_in_paralell/index.md

theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - admonition
#  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - mkautodoc
  - pymdownx.highlight:
      use_pygments: true
  - attr_list
repo_url: https://github.com/entailor/tailor-workflow-gallery/
